# MegaLinter config for ancplua-claude-plugins
# Keep this minimal; tune later if needed.
DEFAULT_BRANCH: main
APPLY_FIXES: none
VALIDATE_ALL_CODEBASE: false
SHOW_ELAPSED_TIME: true
MARKDOWN_SUMMARY_REPORTER: true
